# Generated by Django 3.2.14 on 2023-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclecloth',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
